# Generated by Django 3.2 on 2022-05-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_subscription_id'),
        ('employer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer'),
        ),
    ]
