# Generated by Django 3.2 on 2022-05-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_subscription_id'),
        ('employer_profile', '0002_alter_employerdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('Job_description', models.CharField(max_length=100)),
                ('Job_type', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Subskills', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Notice_time', models.CharField(max_length=100)),
                ('Salary_offered', models.CharField(max_length=100)),
                ('is_draft', models.BooleanField(default='1')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
            ],
        ),
    ]
