# Generated by Django 3.2 on 2022-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0005_auto_20220629_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='industry',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
