# Generated by Django 3.2 on 2022-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0006_alter_employerdetails_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdetails',
            name='job_title',
            field=models.CharField(default='HR', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerdetails',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
