# Generated by Django 3.2 on 2022-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0007_auto_20220719_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='sub_plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('STANDARD', 'STANDARD'), ('PREMIUM', 'PREMIUM')], default='FREE', max_length=140, null=True),
        ),
    ]
