# Generated by Django 3.2 on 2022-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0008_alter_employerdetails_sub_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdetails',
            name='current_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
