# Generated by Django 3.2 on 2022-12-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer_profile', '0009_employerdetails_current_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer_template',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Job_description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Job_type',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Notice_time',
            new_name='notice_time',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Salary_offered',
            new_name='salary_offered',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='employer_template',
            old_name='Subskills',
            new_name='subskills',
        ),
    ]
