# Generated by Django 3.2 on 2022-03-30 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pro_user',
            name='is_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pro_user',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
