# Generated by Django 3.2 on 2022-04-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220330_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Pro_User',
        ),
    ]
