# Generated by Django 3.2 on 2022-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220407_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
