# Generated by Django 3.2 on 2022-04-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_employerdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer'),
        ),
    ]
