# Generated by Django 3.2 on 2022-04-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_employerdetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerDetails',
        ),
    ]
