# Generated by Django 3.2 on 2022-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_employerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
