# Generated by Django 3.2 on 2022-10-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='feedback',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pmf',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
