# Generated by Django 3.2 on 2022-10-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20221003_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Lastlogin1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
