# Generated by Django 3.2 on 2022-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='job_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
