# Generated by Django 3.2 on 2022-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortner', '0003_auto_20221011_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='access_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='shorturl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
