# Generated by Django 3.2 on 2022-04-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0002_alter_subscriptiondetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiondetails',
            name='cancel_at_period_end',
        ),
    ]
