# Generated by Django 3.2 on 2022-04-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_payments', '0003_remove_subscriptiondetails_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
