# Generated by Django 3.2 on 2022-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0004_alter_subscriptiondetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
