# Generated by Django 3.2 on 2022-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0005_subscriptiondetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='plan_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
