# Generated by Django 3.2 on 2022-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0006_subscriptiondetails_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=60, null=True)),
                ('payment_gateway', models.CharField(max_length=60)),
                ('plan_type', models.CharField(blank=True, max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_created', models.DateTimeField(blank=True, null=True)),
                ('plan_amount', models.CharField(max_length=60)),
                ('billing_frequency', models.CharField(blank=True, max_length=60, null=True)),
                ('currency', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
