# Generated by Django 3.2 on 2022-07-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0008_auto_20220713_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='payment',
            new_name='card_id',
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_last_4',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='payment_method',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
