# Generated by Django 3.2 on 2022-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0010_auto_20220718_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='updated_time',
            field=models.DateField(auto_now=True),
        ),
    ]
