# Generated by Django 3.2 on 2022-07-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0012_remove_subscriptiondetails_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='updated_time',
            new_name='updated_at',
        ),
    ]
