# Generated by Django 3.2 on 2022-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0014_alter_subscriptiondetails_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='created_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiondetails',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
