# Generated by Django 3.2 on 2022-07-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0015_auto_20220718_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
