# Generated by Django 3.2 on 2022-07-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0016_rename_created_time_subscriptiondetails_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='card_number',
            new_name='card_network',
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
