# Generated by Django 3.2 on 2022-07-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0017_auto_20220718_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
