# Generated by Django 3.2 on 2022-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0020_subscriptiondetails_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='payment_status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
