# Generated by Django 3.2 on 2022-08-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0021_subscriptiondetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='cancel_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='cancel_at_period_end',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
