# Generated by Django 3.2 on 2022-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0022_auto_20220803_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetails',
            name='billing_reason',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
