# Generated by Django 3.2 on 2022-11-28 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0017_customuser_lastlogin1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.TextField(blank=True, max_length=100, null=True)),
                ('institution_name', models.TextField(blank=True, max_length=100, null=True)),
                ('certificate_name', models.TextField(blank=True, max_length=100, null=True)),
                ('issue_date', models.TextField(blank=True, max_length=100, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('present', models.BooleanField(blank=True, default=False, null=True)),
                ('layout', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePrivateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=230)),
                ('phone_no', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(999999999)])),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('current_salary', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('notice_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Current_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elastic_demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=230)),
                ('age', models.TextField(blank=True, max_length=230)),
                ('school', models.TextField(blank=True, max_length=230)),
                ('location', models.TextField(blank=True, max_length=230)),
            ],
        ),
        
        migrations.CreateModel(
            name='Job_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('areas', models.TextField(blank=True, null=True)),
                ('workplace_type', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('currently_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employer', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('access', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume')),
            ],
        ),
        migrations.CreateModel(
            name='Open_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resp_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('present', models.BooleanField(blank=True, default=False, null=True)),
                ('job_title', models.TextField(blank=True, max_length=100, null=True)),
                ('company_name', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, max_length=100, null=True)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('company_duration', models.IntegerField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, max_length=60, null=True)),
                ('team_count', models.IntegerField(blank=True, null=True)),
                ('my_tasks', models.TextField(blank=True, max_length=1000, null=True)),
                ('layout', models.IntegerField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, max_length=120)),
                ('challenges', models.TextField(blank=True, max_length=300)),
                ('outcome', models.TextField(blank=True, max_length=120)),
                ('learnings', models.TextField(blank=True, max_length=300)),
                ('ext_links', models.TextField(blank=True, max_length=500, null=True)),
                ('access', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume')),
                ('resp_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resp_title')),
                ('skills', models.ManyToManyField(blank=True, to='resume.Skills')),
                ('sub_skills', models.ManyToManyField(blank=True, to='resume.Sub_Skills')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume')),
                ('education', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateeducation')),
                ('misc_detail', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.miscdetail')),
                ('private_data', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateprivatedata')),
                ('work_detail', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.workdetail')),
            ],
        ),
        migrations.AddField(
            model_name='miscdetail',
            name='open_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.open_to'),
        ),
        migrations.AddField(
            model_name='miscdetail',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.status'),
        ),
        migrations.AddField(
            model_name='miscdetail',
            name='timeline',
            field=models.ManyToManyField(blank=True, to='resume.Timeline'),
        ),
        migrations.AddField(
            model_name='candidateprivatedata',
            name='access',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='access',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume'),
        ),
        migrations.AddField(
            model_name='candidateeducation',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.degree'),
        ),
    ]
