# Generated by Django 3.2 on 2022-11-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Task_Suggesstion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('suggessted_tasks', models.TextField(blank=True, null=True)),
            ],
        ),
        
    ]
