# Generated by Django 3.2 on 2022-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20221128_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateeducation',
            name='certificate_name',
        ),
        migrations.RemoveField(
            model_name='candidateeducation',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='candidateeducation',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='candidateprivatedata',
            name='total_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='declared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
