# Generated by Django 3.2 on 2022-12-15 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20221215_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateeducation',
            name='layout',
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.TextField(blank=True, max_length=100, null=True)),
                ('certificate_name', models.TextField(blank=True, max_length=100, null=True)),
                ('issue_date', models.TextField(blank=True, max_length=100, null=True)),
                ('external_links', models.TextField(blank=True, max_length=500, null=True)),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.candidateresume')),
            ],
        ),
    ]
