name: Build and Push Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: shyamayadav154
          password: Shyam@154 
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shyamayadav154/backend-mini
          cache-from: type=registry,ref=shyamayadav154/backend-mini:latest
          cache-to: type=registry,ref=shyamayadav154/backend-mini:latest,mode=max
        