name: Build And Stage Multistage

on: [push]

jobs:
  build-multistage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: shyamayadav154
          password: Shyam@154
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./z
          push: true
          tags: shyamayadav154/backend-test:latest
          cache-from: type=registry,ref=shyamayadav154/backend-test:buildcache
          cache-to: type=registry,ref=shyamayadav154/backend-test:buildcache,mode=max
#
# test caching enabled 2
#
